name: Terraform Deploy

on:
  push:
    branches:
      - main
      - staging
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'staging' && 'staging' || 'dev' }}

    steps:
      # -------------------------
      # Checkout
      # -------------------------
      - uses: actions/checkout@v3

      # -------------------------
      # Azure Login (env-specific)
      # -------------------------
      - name: Azure Login (dev)
        if: github.ref_name == 'dev'
        uses: azure/login@v1.6.1
        with:
          client-id: ${{ secrets.DEV_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DEV_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEV_AZURE_SUBSCRIPTION_ID }}

      - name: Azure Login (staging)
        if: github.ref_name == 'staging'
        uses: azure/login@v1.6.1
        with:
          client-id: ${{ secrets.STAGING_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.STAGING_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.STAGING_AZURE_SUBSCRIPTION_ID }}

      - name: Azure Login (prod)
        if: github.ref_name == 'main'
        uses: azure/login@v1.6.1
        with:
          client-id: ${{ secrets.PROD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PROD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PROD_AZURE_SUBSCRIPTION_ID }}

      # # -------------------------
      # # Terraform (infra + RBAC)
      # # -------------------------
      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v2
      #   with:
      #     terraform_version: 1.6.0

      # - name: Terraform Apply
      #   run: |
      #     cd terraform
      #     terraform init
      #     terraform apply -auto-approve -var="environment=${{ github.ref_name }}"

      # -------------------------
      # Train ML model
      # -------------------------
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install ML deps
        run: pip install pandas scikit-learn joblib

      - name: Train model
        run: python3 ml/data/train.py

      # -------------------------
      # Build & Push Docker image
      # -------------------------
      - name: Login to ACR
        run: az acr login --name acrglobalsend

      - name: Build image
        run:  docker build -f docker/Dockerfile -t acrglobalsend.azurecr.io/globalsend-site:v3 .

      - name: Push image
        run: docker push acrglobalsend.azurecr.io/globalsend-site:v3      

      # -------------------------
      # Restart App Service #
      # -------------------------
      - name: Restart App Service
        run: |
          az webapp restart \
            --name app-globalsend \
            --resource-group globalsend-${{ github.ref_name }}-rg
